/* AUTO-GENERATED by scripts/sync-eventbrite.py — last synced 2026-09-30 */
window.TFC_VENUE = { name: "East Austin Comedy", address: "2505 East 6th Street, Suite D", city: "Austin, TX 78702" };
window.TFC_LINKS = { eventbrite: "https://www.eventbrite.com/o/78517158513", beacons: "https://beacons.ai/evanlopez", linktree: "https://linktr.ee/topflightcomedy" };
window.TFC_SHOWS = [
  {
    "id": "earlyshow",
    "title": "East Austin Comedy Club Early Show",
    "type": "showcase",
    "venue": "East Austin Comedy",
    "address": "2505 East 6th Street, Suite D, Austin, TX 78702",
    "city": "Austin, TX",
    "image": "assets/shows/earlyshow.jpg",
    "ticketUrl": "https://www.eventbrite.com/e/east-austin-comedy-club-early-show-tickets-1032696391707",
    "blurb": "An earlier curtain for a packed night of stand-up \u2014 beat the late crowd and catch a fresh lineup of Austin headliners.",
    "status": "onsale",
    "dates": [
      "2026-10-03T18:00"
    ]
  },
  {
    "id": "humpday",
    "title": "Hump Day Haha's",
    "type": "weekly",
    "venue": "East Austin Comedy Club",
    "address": "2505 East 6th Street, Suite D, Austin, TX 78702",
    "city": "Austin, TX",
    "image": "assets/shows/humpday.jpg",
    "ticketUrl": "https://www.eventbrite.com/e/east-austin-comedy-hump-day-hahas-tickets-1661798918299",
    "blurb": "Get over the hump with Austin's funniest. A midweek stand-up showcase packed with sharp local comics and surprise drop-ins.",
    "status": "onsale",
    "dates": [
      "2026-09-30T20:00"
    ]
  },
  {
    "id": "daywalkers",
    "title": "Daywalkers Comedy Show",
    "type": "showcase",
    "venue": "East Austin Comedy",
    "address": "2505 East 6th Street, Suite D, Austin, TX 78702",
    "city": "Austin, TX",
    "image": "assets/shows/daywalkers.jpg",
    "ticketUrl": "https://www.eventbrite.com/e/top-flight-comedy-presents-daywalkers-comedy-show-tickets-886479824017?aff=oddtdtcreator",
    "blurb": "Tired of late shows? Daywalkers features comics from Netflix, The Comedy Mothership, Cap City, Kill Tony, Skankfest & more.",
    "status": "onsale",
    "dates": [
      "2026-10-02T18:00"
    ]
  },
  {
    "id": "corporate",
    "title": "Corporate & Private Events",
    "type": "corporate",
    "venue": "Your venue or ours",
    "address": "Austin & nationwide",
    "city": "Austin, TX",
    "image": "assets/hero.jpg",
    "ticketUrl": "https://topflightcomedy.com/contact/",
    "blurb": "Fully produced comedy for company parties, conferences, off-sites and private speakeasy nights. Clean or edgy, scalable to 500+ guests.",
    "status": "onsale",
    "dates": []
  }
];
